[project]
name = "project-9"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "boto3>=1.38.14",
    "streamlit>=1.45.1",
]
