[project]
name = "project-9"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "altair>=5.5.0",
    "boto3>=1.38.14",
    "pandas>=2.2.3",
    "plotly>=6.0.1",
    "streamlit>=1.45.1",
]
